name: your-workflow-name
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: "Entrainer le model"
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # le workflow sera ici
          pip install -r requirements.txt
          python train.py

          # Ecrire le rappoart CML
          echo "## Metriques:" >> report.md
          cat results.txt >> report.md
          cml-send-comment report.md
          ls -l
